server:
  context-path: /tipcrm
  port: 8080
tipcrm:
  swagger:
    title: Project of Tip CRM
    description: Tip CRM Swagger UI
    url:
    version: 1.0
    author: neil(1051750377@qq.com), moses(1285823170@qq.com)

spring:
      application:
         name: plm2
      datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://www.potafish.com:3306/TIP_CRM?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
         username:
         password:
      jackson:
         date-format: yyyy-MM-dd HH:mm:ss
#         time-zone: ${TZ}
      jpa:
         show-sql: true
         database-platform: org.hibernate.dialect.MySQL5Dialect
      mail:
        host: smtp.163.com
        username: wan_neil@163.com
        password: 
        default-encoding: UTF-8
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
              ssl:
                enable: true
        port: 465
mail:
      from: wan_neil@163.com