server:
  context-path: /tipcrm
  port: 8080
tipcrm:
  swagger:
    enable: true
    title: Project of Tip CRM
    description: Tip CRM Swagger UI
    url:
    version: 1.0
    author: neil(1051750377@qq.com), moses(1285823170@qq.com)

sentry:
  enable: false
  dsn: https://c6ba06533b624692839f68f116691bb0:11c83623ecb044b0822beaa961307206@sentry.io/295676

uploadfile:
  base-dir: E://

spring:
      application:
         name: plm2
      datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://www.potafish.com:3306/TIP_CRM?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
         username:
         password:
      jackson:
         date-format: yyyy-MM-dd HH:mm:ss
         time-zone: GMT+8
      jpa:
         show-sql: true
         database-platform: org.hibernate.dialect.MySQL5Dialect
      mail:
        host: smtp.163.com
        username: wan_neil@163.com
        password: 
        default-encoding: UTF-8
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
              ssl:
                enable: true
        port: 465
      http:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB

file:
  max-file-size:
    avatar: 1048576
    file: 10485760

mail:
      from: wan_neil@163.com