server:
  context-path: /tipcrm
  port: 8080
tipcrm:
  swagger:
    title: Project of Tip CRM
    description: Tip CRM Swagger UI
    url:
    version: 1.0
    author: neil(1051750377@qq.com), moses(1285823170@qq.com)

spring:
      application:
         name: plm2
      datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://www.potafish.com:3306/TIP_CRM?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
         username:
         password:
      jackson:
         date-format: MM/dd/yyyy hh:mm:ss a
#         time-zone: ${TZ}
      jpa:
         show-sql: true
         database-platform: org.hibernate.dialect.MySQL5Dialect

shiroFilter:
  loginUrl: /login.html
  successUrl: /swagger-ui.html
  unauthorizedUrl: /401.html
  filterChainDefinitionMap:
    /public/api/login: anon
    /public/api/regist: anon
    /regist.html: anon
    /login_assets/**: anon
    /logout: logout
    /**: authc